# This file is not a full hyprland configuration.
# It is intended to be included in your main hyprland.conf.

$activeBorderColor = rgba(f23888ee) rgba(ff6aa7cc) 45deg
$inactiveBorderColor = rgba(4a5d46aa)

general {
    border_size = 1
    gaps_in = 2
    gaps_out = 8
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
}

decoration {
    rounding = 5

    shadow {
        enabled = false
    }

    blur {
        popups = false
    }

    active_opacity = 0.9
    inactive_opacity = 0.8
    fullscreen_opacity = 1.0
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
}
