background            #0b0d11
foreground            #e2c2cc
selection_foreground  #0b0d11
selection_background  #d86f9d

cursor                #d86f9d
cursor_text_color     #0b0d11

active_tab_foreground   #0b0d11
active_tab_background   #d86f9d
inactive_tab_foreground #d8c6cc
inactive_tab_background #0b0d11
tab_bar_background      #0b0d11

# black
color0  #0b0d11
color8  #4a5d46

# red
color1  #d86f9d
color9  #e8a5bc

# green
color2  #356a46
color10 #6b9d72

# yellow
color3  #d7be96
color11 #e6d3b4

# blue
color4  #448755
color12 #7bbf86

# magenta
color5  #e2c2cc
color13 #efd6dd

#cyan
color6  #6f9485
color14 #8bb0a4

#white
color7  #d8c6cc
color15 #f5edf0
